on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yanamura/git-flow-merge-action@v1.2.0
        name: git-flow merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${GITHUB_REF#refs/heads/}
          # git-flowにおけるdevelopブランチの、あなたのリポジトリーにおける名称
          develop_branch: "develop"
          # git-flowにおけるmasterブランチの、あなたのリポジトリーにおける名称
          main_branch: "main"